name: momepy_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - inequality
  - jupyter
  - libpysal>=4.10.0
  - mapclassify
  - matplotlib
  - networkx
  - osmnx
  - pandas!=1.5.0
  - shapely>=2
  - tqdm
  - numba
